# ベクトル演算

ここではベクトルについて成立する演算について説明します．

- ベクトルのスカラー倍
- ベクトルの足し算
- ベクトルの引き算

これらが基本的なベクトルの演算です．
ベクトルについて積の概念もありますが，基本的演算ではないので，ここでは未だ踏み込みません．

### ベクトルのスカラー倍

ベクトルとスカラーの間で掛け算が成立します．
$n$次元列ベクトル$\bf{v}$は，$n$個のスカラーを縦に並べて表現します．

${\bf v} = \left(\begin{array}{c} v_1 \\ v_2 \\ \vdots \\ v_n \end{array} \right)$

スカラー$k$とベクトル$\bf{v}$との掛け算$k{\bf v}$および${\bf v}k$を次のように定義します．
このようにベクトルのスカラー倍を表記する場合は，スカラーとベクトルを並べて記載します．

$k{\bf v} = \left(\begin{array}{c} kv_1 \\ kv_2 \\ \vdots \\ kv_n \end{array} \right)$

${\bf v}k = \left(\begin{array}{cc} v_1k \\ v_2k \\ \vdots \\ v_nk \end{array} \right)$

ここで，スカラーに関しては積の交換法則$ka_i=a_ik$が成り立つので，ベクトルとスカラーの掛け算は可換 $k{\bf v}={\bf v}k$ となります．
そこでベクトルのスカラー倍の表示方法としては，スカラーを左側において$k{\bf v}$と書くのが一般的となっています．

また，ベクトルをスカラーで割ることも，スカラーの逆数を掛けることによって可能となります．
しかし，スカラーをベクトルで割ることはできません．

$\displaystyle 
\frac{\bf v}{k} = \left(\begin{array}{cc} \frac{v_1}{k} \\ \frac{v_2}{k} \\ \vdots \\ \frac{v_n}{k} \end{array} \right)$

### ベクトルの足し算

ベクトルの足し算は，ベクトルの各成分ごとの足し算となります．
そのためベクトルの足し算を行うには，両方のベクトルの次元が等しいことが条件となります．

${\bf u} = \left(\begin{array}{c} u_1 \\ u_2 \\ \vdots \\ u_n \end{array} \right) ,\ \ \ \ $
${\bf v} = \left(\begin{array}{c} v_1 \\ v_2 \\ \vdots \\ v_n \end{array} \right)$

としたとき，${\bf u}+{\bf v}$を次のように定義します．

${\bf u}+{\bf v} = \left(\begin{array}{c} u_1+v_1 \\ u_2+v_2 \\ \vdots \\ u_n+v_n \end{array} \right)$

個々の成分についてはスカラーどうしの足し算となるので，ここでも交換法則が成り立つので，${\bf u}+{\bf v}={\bf v}+{\bf u}$となります．

### ベクトルの引き算

ベクトルの引き算は，引くベクトルに-1を掛けて足し算を行います．
結果としては，ベクトルの各成分ごとの引き算となります．

${\bf u}-{\bf v} = {\bf u}+(-1){\bf v} = \left(\begin{array}{c} u_1-v_1 \\ u_2-v_2 \\ \vdots \\ u_n-v_n \end{array} \right)$


### ベクトルの線形結合

有限個のベクトル${\bf v}_1,{\bf v}_2,\dots,{\bf v}_m$に対して，スカラー$c_1,c_2,\dots,c_m$を用いて
$c_1{\bf v}_1+c_2{\bf v}_2+\dots+c_m{\bf v}_m$
をベクトルの線形結合と言います．
各ベクトルを

${\bf v}_i = \left(\begin{array}{c} v_{i1} \\ v_{i2} \\ \vdots \\ v_{in} \end{array} \right)$

としたとき，

$c_1{\bf v}_1+c_2{\bf v}_2+\dots+c_m{\bf v}_m =
\left(\begin{array}{c}
c_1v_{11}+c_2v_{21}+\dots+c_mv_{m1} \\
c_1v_{12}+c_2v_{22}+\dots+c_mv_{m2} \\ \vdots \\
c_1v_{1n}+c_2v_{2n}+\dots+c_mv_{mn} \end{array} \right)$

となります．

*****
## ベクトル演算の実際

それではベクトルの演算を具体的な例で確認してみましょう．
Pythonでの計算のために配列計算ライブラリーNumPyをimportします．

> <font color=green>import</font> numpy <font color=green>as</font> np

In [1]:
import numpy as np

まずはベクトルのスカラー倍について計算します．
スカラー：$k=3$および，ベクトル：${\bf v} = \left(\begin{array}{c} 9 \\ -3 \\ 6 \end{array} \right)$とした場合に$k{\bf v}$を計算します．

$k{\bf v} = 3 \left(\begin{array}{c} 9 \\ -3 \\ 6 \end{array} \right) 
= \left(\begin{array}{c} 3\times9 \\ 3\times(-3) \\ 3\times6 \end{array} \right)
= \left(\begin{array}{c} 27 \\ -9 \\ 18 \end{array} \right)$

スカラーとベクトルの掛け算をPythonで実施する場合は，数値の掛け算と同様にアスタリスク記号による2項演算「k\*v」と記載します．
まずはスカラー変数kとベクトル変数vを定義します．そしてベクトルのスカラー倍k\*vを実行します．

> k = 3<br>
> v = np.array([9,-3,6])<br>
> k\*v

In [2]:
k = 3
v = np.array([9, -3, 6])
k * v

array([27, -9, 18])

今度は，ベクトルに右からスカラーを掛けてみます．

> v\*k

In [3]:
v * k

array([27, -9, 18])

このようにベクトルのスカラー倍は，左右どちらから掛けても同じ結果が得られることが確かめられました．

次に割り算を行ってみましょう．
スカラーをベクトルで割ることはできませんが，ベクトルをスカラーで割ることはベクトルにスカラーの逆数を掛けることで定義できます．
実践的には，ベクトルの各成分をスカラーで割ることによって求められます．
そこで，${\bf v}\div k$を計算してみます．

${\bf v}\div k = \left(\begin{array}{c} 9 \\ -3 \\ 6 \end{array} \right) \div3 =
\left(\begin{array}{c} 9\div3 \\ -3\div3 \\ 6\div3 \end{array} \right) =
\left(\begin{array}{c} 3 \\ -1 \\ 2 \end{array} \right)$

それではPythonで計算してみましょう．Pythonでの割り算はと「v/k」と記載します．

> v/k

In [4]:
v / k

array([ 3., -1.,  2.])

次にベクトルとベクトルの足し算について確認します．
二つのベクトル${\bf v}_1=\left(\begin{array}{c} 7 \\ -2 \\ 3 \end{array} \right)$および${\bf v}_2=\left(\begin{array}{c} 3 \\ 5 \\ -1 \end{array} \right)$の和を計算します．

${\bf v}_1+{\bf v}_2 = 
\left(\begin{array}{c} 7 \\ -2 \\ 3 \end{array} \right) + \left(\begin{array}{c} 3 \\ 5 \\ -1 \end{array} \right) =
\left(\begin{array}{c} 7+3 \\ -2+5 \\ 3+(-1) \end{array} \right) =
\left(\begin{array}{c} 10 \\ 3 \\ 2 \end{array} \right)$

この計算をPythonで実施します．
ベクトル変数v1,v2をNumPyの配列で定義して，足し算を行います．

> v1 = np.array([7,-2,3])<br>
> v2 = np.array([3,5,-1])<br>
> v1 + v2

In [5]:
v1 = np.array([7, -2, 3])
v2 = np.array([3, 5, -1])
v1 + v2

array([10,  3,  2])

このように定義通りに計算できます．
次に引き算を計算してみましょう．

${\bf v}_1-{\bf v}_2 = 
\left(\begin{array}{c} 7 \\ -2 \\ 3 \end{array} \right) - \left(\begin{array}{c} 3 \\ 5 \\ -1 \end{array} \right) =
\left(\begin{array}{c} 7-3 \\ -2-5 \\ 3-(-1) \end{array} \right) =
\left(\begin{array}{c} 4 \\ -7 \\ 4 \end{array} \right)$

${\bf v}_1$および${\bf v}_2$は，前のセルで定義済みですので，そのまま使用します．

> v1 - v2

In [6]:
v1 - v2

array([ 4, -7,  4])

スカラーとベクトルに関する演算として最初に覚えるべきことはこれだけです．
それでは，理解の定着のために演習問題に取り組みましょう．
*****