# Pythonでの行列とベクトルの積

ここまで，プログラミング言語における数学表現は必ずしも厳密に数学の規則に従っているとは言えない例をいくつか見てきましたが，行列とベクトルの積についてもPythonでの計算には厳密数学とは異なる点があります．
まず，$m$行$n$列の行列と$n$次ベクトルとの積の定義について再度確認します．

行列
$ {\bf A} =
\left(\begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1n} \\ 
a_{21} & a_{22} & \cdots & a_{2n} \\ 
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} \\
\end{array} \right) $
と列ベクトル${\bf v}=\left(\begin{array}{c} v_{1} \\ v_{2} \\ \vdots \\ v_{n} \\ \end{array} \right)$との積${\bf Av}$は下記のようになります．

${\bf A}{\bf v}=
\left(\begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1n} \\ 
a_{21} & a_{22} & \cdots & a_{2n} \\ 
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} \\
\end{array} \right)
\left(\begin{array}{c}
v_{1} \\ 
v_{2} \\ 
\vdots \\
v_{n} \\
\end{array} \right) =
\left(\begin{array}{c}
\sum_{k=1}^{n} a_{1k}v_{k} \\ 
\sum_{k=1}^{n} a_{2k}v_{k} \\ 
\vdots  \\
\sum_{k=1}^{n} a_{mk}v_{k} \\
\end{array} \right) $

この定義は$n$次ベクトルを$n$行$1$列の行列と見なすことで行列の積の理論の下に統一されています．

具体的な例を見て見ましょう．
次の行列${\bf A}$とベクトル${\bf v}$について積をとってみましょう．

${\bf A}=
\left(\begin{array}{ccc}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9 \\
\end{array} \right)$
,
${\bf v}=
\left(\begin{array}{c}
1 \\ 
2 \\ 
3 \\
\end{array} \right)$

行列の積の定義に沿って計算します．

${\bf A}{\bf v}=
\left(\begin{array}{ccc}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9 \\
\end{array} \right)
\left(\begin{array}{c}
1 \\ 
2 \\ 
3 \\
\end{array} \right)
$
$=
\left(\begin{array}{c}
1\times1+2\times2+3\times3 \\ 
4\times1+5\times2+6\times3 \\ 
7\times1+8\times2+9\times3 \\ 
\end{array} \right)
$
$=
\left(\begin{array}{c}
1+4+9 \\ 
4+10+18 \\ 
7+16+27 \\
\end{array} \right)
$
$=
\left(\begin{array}{c}
14 \\ 
32 \\ 
50 \\
\end{array} \right)
$

この計算をPythonで実行するためにNumPyをインポートします．

> <font color=green>import</font> numpy <font color=green>as</font> np

In [1]:
import numpy as np

数学的に正しい定義にそって，${\bf A}$と${\bf v}$を与えて計算します．

> A = np.array([[1,2,3],[4,5,6],[7,8,9]]) <br>
> v2 = np.array([[1],[2],[3]]) <br>
> A.dot(v2)

ここでベクトル変数の名前をあえてv2とします．

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v2 = np.array([[1], [2], [3]])
A.dot(v2)

array([[14],
       [32],
       [50]])

この例で注目することは列ベクトル${\bf v}$の定義が二重配列で3行1列の行列として定義されていることです．
これは数学的定義に全く忠実なプログラムになっています．
Jupyter notebookのCodeセルにて${\bf v}$を表示させてみます．

In [3]:
v2

array([[1],
       [2],
       [3]])

このプログラムは全く正しいです．しかしPythonでのベクトルの取扱い方法は単純配列としていました．

> v1 = np.array([1,2,3]) <br>
> v1

In [4]:
v1 = np.array([1, 2, 3])
v1

array([1, 2, 3])

それでは，このように定義して行列とベクトルの積を計算しましょう．

> A.dot(v1)

In [5]:
A.dot(v1)

array([14, 32, 50])

数学的定義と厳密には合っていませんが，Pythonの中でこのように使われています．
数学の理論を理解する上では厳密性が重要になりますが，プログラミングにおいては柔軟性を受け入れることをお勧めします．
*****