# 配列に対する操作(1)
- スライス(添え字)

In [12]:
import numpy as np

In [13]:
# 始点を省略 0 〜　 20 未満
a = np.arange(20) * 2
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [14]:
print(a[1:6])

[ 2  4  6  8 10]


## 配列形状の変形

In [15]:
a = np.arange(30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [16]:
# 一次元配列を二次元配列に変換する
a2 = a.reshape((5, 6))
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


object.reshape(行size, 列size) で配列の形式を変換

In [17]:
# 三次元配列に変換する
a3 = a2.reshape((2, 3, 5))
print(a3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [18]:
# 高次元配列を平坦化する
print(a3.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


object.flatten()　->　平坦化する: flatten（フラトン）

In [19]:
# flatten より処理が速いものがある
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


object.ravel()　->　sizeが物凄く大きな高次元配列を高速で平坦化できる　： ravel(ラベル)

## 配列の転置

- 転置 -> 方向を変える(ひっくり返す)事ができる

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


#### object.T

- 3行の２列になる
    - 元の配列を対角線で裏返す感じ。 1 -> 6, 4 -> 3
    - 転置行列を作るときにこの処理がそのまま使用できる

### まとめ
- 配列のスライス (添字)
    - １つの整数を指定　:　その index 位置の要素にアクセス

- 配列の変形
    - reshape(配列次元の構成)　:　次元の構成を tuple で与える
    - flatten(), ravel()　:　高次元配列を一次元に(平坦化)する ※ ravel()が推奨されている
        - ravel()の方が高速で処理できる
    - T プロパティ　:　行,列を入れ替える　(転置：　Transpose:トランスポーズ) 
    

# 配列に対する操作(2)
- スライスの高度な使い方
- 行、列の反転・回転

### スライスにlistやarray(配列)を与える
- numpy のスライスは　python の list の配列よりもっと高度な事ができる

In [23]:
a = np.arange(10) * 10
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [24]:
# スライスの中に list や　配列を与える
a2 = a[[1, 3, 5]]
print(a2)

[10 30 50]


指定した　index　を抜き出して、 a2 に代入する

- 抜き出したい要素を　list や配列で抽出できる

- numpy 配列独自のモノ

In [25]:
# 複数の index を指定してまとめて値を変更する
a[[1, 3, 5]] = [[7, 8, 9]]
print(a)

[ 0  7 20  8 40  9 60 70 80 90]


### 行・列の反転・回転
- 順番を逆転させる

In [26]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
# 反転させる
print(np.flip(a))

[9 8 7 6 5 4 3 2 1 0]


In [28]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


-　np.flip(反転したい配列) : numpy library のfunction

- flip 関数は反転した物を別の配列として返す　function
    - 非破壊 -> 全く手を加えず、反転した結果の別の配列を返す

In [30]:
# 二次元の配列に対して flip function を使用
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
np.flip(a2)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

- 多次元の配列に対して flip function を使用すると、記述した順番を逆転した形で抽出される

- 同じ形状の多次元の配列として返してくる