# zip object(ジップオブジェクト)

- data 列を束ねる「zip」
    - data 処理の様々な局面で必要になるもの
    - python3 に備わっている機能
    - data 処理で特にお世話になる機能
    
- 様々な data列を束ねて１つの集合体として扱って効率的に　data処理を行う


In [3]:
import numpy as np

In [4]:
a1 = [1, 3, 5, 7, 9]
a2 = [2, 4, 6, 8, 10]
z = zip(a1, a2)

In [6]:
z

In [7]:
print(z)

- zip object 特殊な object　：　強引に list に変換する事もできる

- python は型の違う　data構造のモノをかなり自在に変換できる

In [8]:
list(z)

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]

- tuple()型に変換されて　->　a1, a2 が束ねられている　->　1と2, 3と4, ect...

- <u>先頭から取り出して１個づつペアにしている</u>　=　束ねられている

- zip　->　色々なdata構造を束ねて一直線のdata構造にする
    - zip object できた時は何を意味しているか分からない　->　変換の仕方によって変わるから　->　束ねられたモノとして存在する

#### zip object は使い捨ての　data構造なので、1回使用したら使用できなくなる

In [9]:
list(z)

[]

- z の要素は,1回消費され使い終わったものとして中身が空っぽになる

- なぜこのような特質を持つのか？
    - 束ねたものを何に使用するのか？
    - for loop など順番に要素を取り出して使用される。全て使用されれば　for loopは終了する
    - 上記のような使用のされ方が多いので、使い捨ての特徴をもつ

In [12]:
z = zip(a1, a2)
a = np.array(z)
print(a)

- 上記のやり方では zip object は配列にできない

- 一度listに変換してから配列に変換する

In [14]:
z = zip(a1, a2)
a = np.array(list(z))
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [15]:
print(a1); print(a2)

[1, 3, 5, 7, 9]
[2, 4, 6, 8, 10]


#### 5行・2列の配列として作成される

## 様々なdata列を束ねる

In [16]:
z = zip(a1, 'あいうえお')

In [17]:
list(z)

[(1, 'あ'), (3, 'い'), (5, 'う'), (7, 'え'), (9, 'お')]

### integer と string, string と　string も束ねることができる

In [20]:
z = zip('abcde', 'あいうえお', 'かきくきこ')
list(z)

[('a', 'あ', 'か'),
 ('b', 'い', 'き'),
 ('c', 'う', 'く'),
 ('d', 'え', 'き'),
 ('e', 'お', 'こ')]

先頭から1個づつ取り出して束ねる

## dectionary型(辞書型)

In [21]:
e = ['dog', 'cat', 'bird']
j = ['犬', '猫', '鳥']
z = zip(e, j)
list(z)

[('dog', '犬'), ('cat', '猫'), ('bird', '鳥')]

In [22]:
e = ['dog', 'cat', 'bird']
j = ['犬', '猫', '鳥']
z = zip(e, j)

In [23]:
# dictionary に変換
d = dict(z)

In [24]:
d

{'dog': '犬', 'cat': '猫', 'bird': '鳥'}

#### <u>dict(z) でも変換はできるが、 list(z) に変換する操作をしておく方が安全な習慣</u>

In [25]:
e = ['dog', 'cat', 'bird']
j = ['犬', '猫', '鳥']
z = zip(e, j)
d = dict(list(z))

In [28]:
d

{'dog': '犬', 'cat': '猫', 'bird': '鳥'}

In [29]:
d['dog']

'犬'

## 繰り返し処理の応用

In [34]:
a1 = [1, 2, 3]
a2 = [4, 5, 6]
z = zip(a1, a2)

In [35]:
for x, y in z:
    print(x, y)

1 4
2 5
3 6


In [39]:
a1 = [1, 2, 3]
a2 = [4, 5, 6]
z = zip(a1, a2)

In [40]:
for x, y in z:
    print(x, '+', y, '=', x+y)

1 + 4 = 5
2 + 5 = 7
3 + 6 = 9


In [42]:
for i in range(5):
    print(i)

0
1
2
3
4


#### data 処理に進む場合は,上記の解釈を変える必要がある
- 5回繰り返すではなく…

- 0 ~ 4 までの列を扱ったという解釈
    - 0 ~ 4 までの data列それぞれのについて　i　を取り出しその　i　を印字する


- data処理として考える場合は　in　の後ろは　data列という解釈
    - data列1個1個の中身を取り出しながら、何かをする

In [43]:
r = range(10)

In [44]:
r

range(0, 10)

In [45]:
list(r)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- range も謎の range object であった…

### まとめ
- zip 関数　:　複数のデータ列を束ねて、一本のデータ列にする
    - 様々な型のdata列(list, array, dectionary, string,ect...)を束ねる事ができる
    - タイプ・種類の違う型を強引に束ねる事ができる
    - zip object (使い捨て)　->　何かしら変換するまでは、束ねたモノとして存在する　： range()も共通する
    - iterator(イテレーター)　:　繰り返しの処理の抽象化, 使い捨てdata列, 
    - 別のdata構造に変換することができる。(array, list, dictionary, ect...)

# 要素の整列
- dataの並びを並び替える
    - sort( )　:　関数(function)
    - .sort　:　メソッド(method)

In [46]:
a = np.array([3, 5, 1, 4, 2, 6])
print(a)

[3 5 1 4 2 6]


## sort(　) : 関数
- 元の配列を壊さない
- 整列したモノは、別の配列として生成される

In [47]:
a2 = np.sort(a)
print(a2)

[1 2 3 4 5 6]


In [49]:
print(a)

[3 5 1 4 2 6]


## .sort( ) : method
- 配列 object に働きかけるような method
- 元の配列を変更する
- 値と配列そのものを変更する(昇順にする)

In [50]:
a.sort()

In [51]:
print(a)

[1 2 3 4 5 6]


In [52]:
a = np.array([3, 4, 2, 5, 6, 1])
print(a)

[3 4 2 5 6 1]


### 逆順にする（降順）
- no.sort(a)[::-1]
    - スライスを使用して、生成されたモノを降順にする

In [53]:
a2 = np.sort(a)[::-1]
print(a2)

[6 5 4 3 2 1]


In [55]:
a2 = np.flip(np.sort(a))
print(a2)

[6 5 4 3 2 1]


### 整列後のindexを得る
- 整列後の index を取得するのではなく、整列前の index を取得する

- argsort
    - 整列結果の元の index が返される
    - 整列前のバラバラの並びの時の　index が取得できる

#### <u>argsort は機械学習・深層学習でしばしば使用する機能</u>
- そもそもどこにあったのか…という事が大切になってくる

In [58]:
# .argsort() : method/配列　object に対して行うもの
a2 = a.argsort()
print(a2)

[5 2 0 1 3 4]


### まとめ
- <u>sort()　:　関数</u>
    - np.sort(配列)
        - 配列を昇順に整列したもの
        - 元の配列はそのまま保つ

- <u>.sort()　:　method</u>
    - (配列).sort()
        - 配列の要素を昇順に整列する
        - 対象の配列の内容を変更する形で整列

- <u>使い分け</u>
    - メモリを節約したいケースで　.sort() : method が役に立つ事がある
        - メモリ容量がとてつもなく大きい物を並べ替える時に sort() : 関数を使用してしまうと…
        - **とてつもなく大きいdataが２倍になってしまうから　.sort() : method を使用する**
        - 主たる目的とは言えないのだが、そういう使い分けがある

- <u>反転</u>
    - 配列[ ::-1 ]　:　降順　※ default は昇順
        - スライス（超高速で反転）
    - np.flip(a)　:　降順に入れ替え
    - 共に元の配列を変更しない