# 配列に対する操作(1)
- スライス(添え字)

In [2]:
import numpy as np

In [3]:
# 始点を省略 0 〜　 20 未満
a = np.arange(20) * 2
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [4]:
print(a[1:6])

[ 2  4  6  8 10]


## 配列形状の変形

In [5]:
a = np.arange(30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [6]:
# 一次元配列を二次元配列に変換する
a2 = a.reshape((5, 6))
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


object.reshape(行size, 列size) で配列の形式を変換

In [7]:
# 三次元配列に変換する
a3 = a2.reshape((2, 3, 5))
print(a3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [8]:
# 高次元配列を平坦化する
print(a3.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


object.flatten()　->　平坦化する: flatten（フラトン）

In [9]:
# flatten より処理が速いものがある
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


object.ravel()　->　sizeが物凄く大きな高次元配列を高速で平坦化できる　： ravel(ラベル)

## 配列の転置

- 転置 -> 方向を変える(ひっくり返す)事ができる

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


#### object.T

- 3行の２列になる
    - 元の配列を対角線で裏返す感じ。 1 -> 6, 4 -> 3
    - 転置行列を作るときにこの処理がそのまま使用できる

### まとめ
- 配列のスライス (添字)
    - １つの整数を指定　:　その index 位置の要素にアクセス

- 配列の変形
    - reshape(配列次元の構成)　:　次元の構成を tuple で与える
    - flatten(), ravel()　:　高次元配列を一次元に(平坦化)する ※ ravel()が推奨されている
        - ravel()の方が高速で処理できる
    - T プロパティ　:　行,列を入れ替える　(転置：　Transpose:トランスポーズ) 
    

# 配列に対する操作(2)
- スライスの高度な使い方
- 行、列の反転・回転

### スライスにlistやarray(配列)を与える
- numpy のスライスは　python の list の配列よりもっと高度な事ができる

In [ ]:
a = np.arange(10) * 10
print(a)

In [ ]:
# スライスの中に list や　配列を与える
a2 = a[[1, 3, 5]]
print(a2)

指定した　index　を抜き出して、 a2 に代入する

- 抜き出したい要素を　list や配列で抽出できる

- numpy 配列独自のモノ

In [ ]:
# 複数の index を指定してまとめて値を変更する
a[[1, 3, 5]] = [[7, 8, 9]]
print(a)

### 行・列の反転・回転
- 順番を逆転させる

In [16]:
a = np.arange(10)
print(10)

10


In [17]:
# 反転させる
print(np.flip(a))

[9 8 7 6 5 4 3 2 1 0]


In [18]:
# 元の配列はどうなっているのか
print(a)

[0 1 2 3 4 5 6 7 8 9]


-　np.flip(反転したい配列) : numpy library のfunction

- flip 関数は反転した物を別の配列として返す　function
    - 非破壊 -> 全く手を加えず、反転した結果の別の配列を返す

In [20]:
# 二次元の配列に対して flip function を使用
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
np.flip(a2)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

- 多次元の配列に対して flip function を使用すると、記述した順番を逆転した形で抽出される

- 同じ形状の多次元の配列として返してくる

### flip 関数が必要な場合とは?

In [28]:
# 行の方向で反転　: axis = 0
print(np.flip(a2, axis=0))

[[7 8 9]
 [4 5 6]
 [1 2 3]]


- 各行の順番が逆になっている : axis -> どの形、どの順番で、どの軸を元にして反転させるのか

np.flip(反転対象, axis=引数)

In [29]:
# 列の方向で反転 : axis = 1
print(np.flip(a2, axis=1))

[[3 2 1]
 [6 5 4]
 [9 8 7]]


#### 二次元配列は、方向を指定して、軸を指定して、順番を逆転することができる
- 表形式の順番を逆転させる時に使用

### 行・列を回転させる

In [30]:
print(np.roll(a2, shift=1))

[[9 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- np.roll(配列, shift=ずらす数)

- １つずつズレる。最後にはみ出た 9 が先頭に戻る -> 回転して戻る

In [32]:
print(np.roll(a2, shift=3))

[[7 8 9]
 [1 2 3]
 [4 5 6]]


#### 行方向・列方向に指定して回転させる事もできる

In [36]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
# 行方向に１つズレる
print(np.roll(a2, shift=1, axis=0))

[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [37]:
# 行を2つズラす
print(np.roll(a2, shift=2, axis=0))

[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [41]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
# 列方向に１つズラす
print(np.roll(a2, shift=1, axis=1))

[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [43]:
# 列方向に2つズラす
print(np.roll(a2, shift=2, axis=1))

[[2 3 1]
 [5 6 4]
 [8 9 7]]


### まとめ
- <u>スライスに data列(list,array)を与えるこ</u>
    - 複数の　index 位置の要素をまとめて取り出す(まとめて代入も可)
    
- <u>反転(順序の逆転)</u>
    - np.flip(配列)　　:　データ列の反転
        - np.〇〇()　:　関数(反転したいモノ)
        - 反転した物は別のモノとして返される

- <u>axis(0~1) : 0 = 行, 1 = 列</u>
    - どの軸で指定する時に使用する
    - np.flip(配列, axis=0)　:　行の順序が逆になったモノを返す(上下が反転)
    - np.flip(配列, axis=1)　:　列の順序が逆になったモノを返す(左右が反転)

- <u>回転(順序をずらす)</u>
    - np.roll(配列, shift=移動量)　:　データの並びをずらす
    - np.roll(配列, shift=移動量, axis= 0 or 1)　:　0 = 行をズラす, 1 = 列をズラす


# 配列の編集(1)
- 配列の連結
    - append()　:　関数
    - concatenate()　:　関数

### 配列の連結

In [45]:
# 一次元の配列を作成
a1 = np.array([0, 1, 2])
a2 = np.array([3, 4, 5])
print(a1); print(a2)

[0 1 2]
[3 4 5]


In [47]:
a = np.append(a1, a2)
print(a)

[0 1 2 3 4 5]


In [48]:
a1 = np.zeros((2, 4))
a2 = np.ones((2, 4))
print(a1); print(a2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [49]:
a = np.append(a1, a2)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 多次元の場合は連結する方向を意識しないと、上記のようになる
- 引数に axis=0 or 1 : 行か列か引数を指定する事

In [53]:
# 行を指定して連結 :　縦方向に連結
a = np.append(a1, a2, axis=0)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [54]:
# 列を指定して連結 : 横方向に連結
a = np.append(a1, a2, axis=1)
print(a)

[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


#### append() は、２つの配列を連結する為の関数 = 3つの連結はできない

## concatenate(コンケイトネント)
-　配列の複数の連結の時に用いる

In [55]:
a1 = np.zeros((2, 2)); a1.fill(1)
a2 = np.zeros((2, 2)); a2.fill(2)
a3 = np.zeros((2, 2)); a3.fill(3)

print(a1); print(a2); print(a3)

[[1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]]
[[3. 3.]
 [3. 3.]]


In [57]:
a = np.concatenate((a1, a2, a3), axis=0)
print(a)

[[1. 1.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [3. 3.]
 [3. 3.]]


In [58]:
a = np.concatenate((a1, a2, a3), axis=1)
print(a)

[[1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]]


#### データ処理の世界では、複数の配列を望みの形に連結する事はよくある

### 縦方向専用・横方向専用に繋げる funcion
- axis=0, axis=1 と同じ働きをする


In [59]:
a = np.vstack((a1, a2, a3))
print(a)

[[1. 1.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [3. 3.]
 [3. 3.]]


In [60]:
a = np.hstack((a1, a2, a3))
print(a)

[[1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]]


## 配列を繰り返し
- 配列を繰り返してタイルのように並べていく
- ある配列を敷き詰めることによってより大きな配列を作成する

In [65]:
# 二次元配列を作成
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [68]:
# 横方向に散りばめて繰り返していく
a2 = np.tile(a, (3, 1))
print(a2)

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]


np.tile(配列, (行, 列)) : 縦横に何回ずつ繰り返すのか？ shape tuple で入力

In [69]:
a2 = np.tile(a, (2, 3))
print(a2)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


### まとめ
- <u>配列の連結</u>
    - np.append(配列１, 配列2, axis=0 or 1)　:　2つの配列を行　or　列方向に連結
        - axis　を省略すると平坦化されて一次元になる
- <u>複数連結</u>
    - concatenate((配列１, 配列2, 配列3), axis=0 or 1)　:　行 or 列方向に連結
        - 3つ以上 tuple型で繋げて記述

    - vstack(縦専属連結), hstack(横専属連結)　という function もある

- <u>配列の繰り返し</u>
    - np.tile(配列, (縦の回数, 横の回数))

# 配列の編集(2)
- 配列への要素の挿入と削除
    - insert(　)　:　関数
    - delete(　)　:　関数

## 要素の挿入

In [70]:
a = np.array([0, 1, 2, 3, 4, 5])
ins = np.array([10, 20, 30])
print(a); print(ins)

[0 1 2 3 4 5]
[10 20 30]


In [71]:
# insert をして挿入していく
a2 = np.insert(a, 3, ins)
print(a2)

[ 0  1  2 10 20 30  3  4  5]


np.insert(元の配列, 挿入index, 挿入する配列)

In [72]:
# 1つの数値を挿入する事もできる
a2 = np.insert(a, 2, 99)
print(a2)

[ 0  1 99  2  3  4  5]


### 多次元の配列に行・列を挿入する

In [75]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ins = np.array([91, 92, 93])
print(a); print(ins)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[91 92 93]


In [76]:
a2 = np.insert(a, 2, ins, axis=0)
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [91 92 93]
 [ 7  8  9]]


- np.insert(元の配列, index 2, 挿入する配列, axis=行)

- 行の　index 2 の場所に挿入される

In [77]:
# 列方向に insert する
a2 = np.insert(a, 2, ins, axis=1)
print(a2)

[[ 1  2 91  3]
 [ 4  5 92  6]
 [ 7  8 93  9]]


In [78]:
# 挿入する方を多次元にする
ins2 = np.array([[91, 92, 93], [94, 95, 96], [97, 98, 99]])
print(ins2)

[[91 92 93]
 [94 95 96]
 [97 98 99]]


In [79]:
a2 = np.insert(a, 2, ins2, axis=0)
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [91 92 93]
 [94 95 96]
 [97 98 99]
 [ 7  8  9]]


In [80]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
a2 = np.insert(a, 2, ins2, axis=1)
print(a2)

[[ 1  2 91 94 97  3]
 [ 4  5 92 95 98  6]
 [ 7  8 93 96 99  9]]


- 列に挿入する時は転置されてしまうので注意する

- よく使用されるのは axis=0 （行）の方が圧倒的に多い

## 要素の削除

In [82]:
a = np.array([0, 2, 3, 4, 5])
print(a)

[0 2 3 4 5]


In [86]:
a2 = np.delete(a, 2)
print(a2)

[0 2 4 5]


In [87]:
print(a)

[0 2 3 4 5]


delete しても元の a が壊されるわけではない

In [88]:
# 多次元の配列を部分的に削除
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [90]:
a2 = np.delete(a, 2, axis=0)
print(a2)

[[1 2 3]
 [4 5 6]]


In [92]:
a2 = np.delete(a, 2, axis=1)
print(a2)

[[1 2]
 [4 5]
 [7 8]]


### まとめ
- <u>要素の挿入</u>
    - np.insert(配列1, 挿入index, 挿入要素, axis=0 or 1)
        - 「配列」の「挿入位置」の行　or 列に「挿入要素」を挿入する
        - 配列が一次元の場合は axis は不要

- <u>要素の削除</u>
    - np.delete(配列1, 削除index, axis=0 or 1)
        - 「配列」の「削除位置」の行 or 列を削除する

# データ抽出
- ある条件を満たす要素を取り出す
- 最大値、最小値を取り出す

### 要素の抽出

In [94]:
# スライス
a = np.arange(4)
print(a)

[0 1 2 3]


In [96]:
# True or False (真理値)
msk = [False, True, False, False]
a2 = a[msk]
print(a2)

[1]


- numpy の配列は真理値の配列も与えることができる

- a[真理値の並び]　-> True　に対応するモノを抜き出す事ができる

- 欲しい要素の配列の位置を True とする

In [97]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [99]:
# 配列に剰余を求めるとどうなるのか？
m = a % 2 == 0 
print(m)

[ True False  True False  True False  True False  True False]


### 配列に対して条件式を行うと…
- 各配列要素に対して剰余値の結果を真理値で出力する ->　Treu or False
- 2 で割った余りが 0 であるかどうか？
- 配列一括処理の一種

#### 配列のスライスの中に直接、条件式を記述する事ができる

### 条件式による要素の抽出

In [104]:
a2 = a[a%2==0]
print(a2)

[0 2 4 6 8]


### 上記のやり方は、今後 data 処理で現場で必ず必要になる基礎的な手法
- 配列のスライスの中に直接、条件式を記述して欲しい情報だけを抽出する
    - <u>条件式の返り値　->　True or False なので　->　条件式が True のものが抽出される</u>
    - **元になる配列[ 条件式 ]**
    - python にはない Numpy 独自の機能

In [106]:
a2 = a[a>5]
print(a2)

[6 7 8 9]


## where による狙い撃ち
- np.where()　:　function(関数)
    - np.where( 対象配列に対する条件式,　'条件に対するアクション',　アクション以外の配列要素 )

In [107]:
a2 = np.where(a > 5, 'big', a)
print(a2)

['0' '1' '2' '3' '4' '5' 'big' 'big' 'big' 'big']


5より大きい部分には　big をそれ以外の部分には元の data を出力する

In [108]:
a2 = np.where(a % 2==0, '偶', '奇')
print(a2)

['偶' '奇' '偶' '奇' '偶' '奇' '偶' '奇' '偶' '奇']


In [109]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


## 配列の最大値・最小値

In [110]:
a = np.array([1, 2, 3, 4, 3, 2, 1])
print(a)

[1 2 3 4 3 2 1]


In [112]:
# .max() : method
a.max()

4

In [113]:
# .min() : method
a.min()

1

### まとめ
- <u>配列のスライスに条件式を与え、その条件式を満たす要素を取り出す(NumPyでは可能)</u>
    - 配列[ 条件式 ]
        - <u>配列の条件式は真理値の列を返す</u>
        - True or False の配列　->　スライスの中に真理値の並びを与えている

- <u>与えられた条件によって処理を施す</u>
    - np.where(　条件式,　真(True)となる要素に対して処理,　偽(False)となる要素に対する処理　)