# 多次元配列

- 二次元の配列
    - 「行」と「列」の2方向に広がる配列 (表のような配列)
    - 表 data (tabel data)

In [1]:
import numpy as np

In [2]:
A = np.array([[11, 12], [21, 22]])
print(A)

[[11 12]
 [21 22]]


In [3]:
A[0, 0]

11

In [4]:
A[0, 1]

12

[行 : 列]

In [5]:
A[1, 0]

21

In [6]:
A[1, 1]

22

In [7]:
A.shape

(2, 2)

tuple型 で帰ってくる　->　2行 : 2列 を持った配列

### 参考
- list のように出力できる
- 実際は array に関しての出力は, (コンマ)で区切るのが正しいやり方

In [9]:
A[1][1]

22

### まとめ
- 二次元配列は 「一次元の配列を並べたもの」と見ることができる
- 要素へのアクセス : 配列[i, j]　->　[i行目 : j行目]
- 配列の形状を調査　:　配列.shape　->　各方向(各次元)のサイズの tuple
    - shape はプロパティであり、　function, method とは異なる　※ 関数、メソッドの場合は () つける
        - 末尾の括弧と引数は不要

# 多次元配列（2）
- 多次元配列の作成

1. list を配列変換する　->　np.array(list型)

2. <u>特定の値を並べた配列を作成する</u>

### 1や0を並べた配列

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- 1 が 10 個出力される

- 浮動小数点数 : float

- いちいち list化して記述しなくて済む

In [11]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
# 欲しい　shape の tuple型を引数に記述する
print(np.ones((2, 2)))

[[1. 1.]
 [1. 1.]]


In [15]:
# 5行・5列
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 既存の配列編集

In [18]:
# 1行　・ 1列
z[1, 1] = 3
print(z)

[[0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 特定の値で配列を満たす

In [20]:
z.fill(7)
print(z)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


#### fill　->　満たすという事

- 新たに 0 ばかりの配列を作成するには zeros が使用できるが

- fill 既にある配列を埋め尽くすときに使用する

# 3次元の配列
- 「二次元の表が複数ある」と見る事ができる
- 二次元配列が,2段ある (上下にある： layer みたいなもの)

### 3次元の配列

In [24]:
a3d = np.array([[[111, 112,], [121, 122]], [[211, 212], [221, 222]]])
print(a3d)

[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]]


In [25]:
a3d.shape

(2, 2, 2)

(段, 行, 列)

In [26]:
a3d[0, 1, 1]

122

In [27]:
a3d[1, 0, 1]

212

### まとめ
- 「１」　を並べた配列を作る
    -　np.ones((行size, 列size))
    
- 「０」　を並べた配列を作る
    - np.zeros((行size, 列size))
    
- 配列は事後に編集する事もできる
    - z[1,1]　=　3 (３に書き換える)
    - fill　　->　全て指定した値に置き換える

- 三次元配列へのアクセス
    - a3d[段, 行, 列]
    - 2次元の表が何段もあるモノという理解

#### 段数もindexと同じで 0 段とは普通の 1段目にあたる
