# 転置
転置により、行列の行と列を入れ替えます。人工知能のコードでは転置を頻繁に使います。

### 転置とは？

行列に対する重要な操作に、**転置**というものがあります。行列を転置することにより、行と列が入れ替わります。以下は転置の例ですが、例えば行列$A$の転置行列は$A^{\mathrm{T}}$と表します。  

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) \\
   A^{\mathrm{T}} & = \left(
    \begin{array}{cc}
      1 & 4 \\
      2 & 5 \\
      3 & 6 \\
    \end{array}
  \right) \\
\end{aligned} $$ 

$$  \begin{aligned} \\
   B & = \left(
    \begin{array}{cc}
      a & b \\
      c & d \\
      e & f \\
    \end{array}
  \right) \\
   B^{\mathrm{T}} & = \left(
    \begin{array}{ccc}
      a & c & e \\
      b & d & f \\
    \end{array}
  \right) \\
\end{aligned} $$ 

### 転置の実装
Numpyにおいては、行列を表す配列名の後に`.T`を付けると転置されます。

In [2]:
import numpy as np
import sympy as sp
sp.init_printing()

In [5]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])

mat1 = sp.Matrix(a)

print(f'a の行列:\n{a}\n\na の転置行列:\n{a.T}\n')
display(mat1, mat1.T)

a の行列:
[[1 2 3]
 [4 5 6]]

a の転置行列:
[[1 4]
 [2 5]
 [3 6]]



⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

### 行列積と転置
行列積においては、基本的に前の行列の列数と、後ろの行列の行数が一致する必要があります。しかしながら、一致しなくても転置により行列積が可能になる場合があります。  
下の図のようなl$\times$nの行列$A$と、m$\times$nの行列$B$を考えます。$n\neq m$とします。

<img src="images/product_impossible.png">

この場合は、行列$A$の列数がnであり、行列$B$の行数がmで等しくないので、行列積はできません。しかしながら、行列$B$を転置することにより、下の図で示すように行列積が可能になります。

<img src="images/product_possible.png">

行列$A$の列数と、行列$B^{\mathrm{T}}$の行数が等しくなり、行列積が計算できるようになりました。  

### 転置と行列積の実装
以下は、Numpyの配列を転置し、行列積を計算している例です。配列名のあとに```.T```をつけると、転置行列になります。

In [11]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])

mat1 = sp.Matrix(a)

print(f'a行列:\n\n{a}\n')
display(mat1)

b = np.array([[1, 2, 3],
             [4, 5, 6]])

mat2 = sp.Matrix(b)
mat2_t = mat2.T

print(f'\nb行列:\n\n{b}\n\nbの転置行列:\n\n{b.T}\n')
display(mat2, mat2_t)

mat3 = mat1 * mat2.T


# b = b.T
print(f'\na行列, bの転置行列積:\n\n{np.dot(a, b.T)}\n')
display(mat3)

a行列:

[[1 2 3]
 [4 5 6]]



⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦


b行列:

[[1 2 3]
 [4 5 6]]

bの転置行列:

[[1 4]
 [2 5]
 [3 6]]



⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦


a行列, bの転置行列積:

[[14 32]
 [32 77]]



⎡14  32⎤
⎢      ⎥
⎣32  77⎦

上記のコードでは、行列`b`を転置することで行数が3になり、行列`a`の列数と一致するので行列積が可能になっています。  

### 演習:
以下のセルで行列aもしくは行列bを転置し、行列aと行列bの行列積を計算しましょう。

In [17]:
a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

mat1 = sp.Matrix(a)

print(f'a行列:\n\n{a}\n')
display(mat1)


b = np.array([[0, 1, 2],
              [2, 3, 4]]) 

mat2 = sp.Matrix(b)

print(f'\nbの行列:\n\n{b}\n')
display(mat2)

# 行列積
print(f'\naを転置:\n\n{a.T}\n')
display(mat1.T)

mat3 = mat1.T * mat2

print(f'\nabの行列積\n\n{a.T.dot(b)}\n')
display(mat3)


a行列:

[[0 1 2]
 [1 2 3]]



⎡0  1  2⎤
⎢       ⎥
⎣1  2  3⎦


bの行列:

[[0 1 2]
 [2 3 4]]



⎡0  1  2⎤
⎢       ⎥
⎣2  3  4⎦


aを転置:

[[0 1]
 [1 2]
 [2 3]]



⎡0  1⎤
⎢    ⎥
⎢1  2⎥
⎢    ⎥
⎣2  3⎦


abの行列積

[[ 2  3  4]
 [ 4  7 10]
 [ 6 11 16]]



⎡2  3   4 ⎤
⎢         ⎥
⎢4  7   10⎥
⎢         ⎥
⎣6  11  16⎦