# 行列式と逆行列
行列式を使うことにより、行列の「逆行列」を求めることができます。逆行列を使えば、行列の方程式を解くことなどが可能になります。

### 単位行列とは？

**単位行列**は、以下のような行列のことです。  

$$
E = \left(
    \begin{array}{cc}
      1 & 0 \\
      0 & 1 \\
    \end{array}
  \right) 
$$ 

このように、単位行列では左上から右下に1が並び、その他の要素は0になります。  
上記は$2\times 2$の単位行列になります。  

以下に示すように、単位行列には行列の前後に行列積でかけても行列を変化させない、という特徴があります。
$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{ccc}
      a & b \\
      c & d \\
    \end{array}
  \right) \\
   EA & = \left(
    \begin{array}{ccc}
      a & b \\
      c & d \\
    \end{array}
  \right) \\
  AE & = \left(
    \begin{array}{ccc}
      a & b \\
      c & d \\
    \end{array}
  \right) \\
\end{aligned} $$ 

### 単位行列の実装
NumPyにおいては、eye()関数により単位行列を作成することができます。

In [1]:
import numpy as np
import sympy as sp
sp.init_printing()

In [3]:
# eye は単位行列を表す
mat1 = sp.eye(2)

print(f'単位行列:\n\n{np.eye(2)}\n')
display(mat1)

単位行列:

[[1. 0.]
 [0. 1.]]



⎡1  0⎤
⎢    ⎥
⎣0  1⎦

### 逆行列とは？
以下に例を示すように、ある数値とその逆数をかけると1になります。 

$$3\times \frac{1}{3} = 1$$
$$21\times \frac{1}{21} = 1$$

逆数と同じように、行列にもかけると単位行列になる行列が存在することがあります。  
このような行列を、**逆行列**といいます。  
行列$A$の逆行列を$A^{-1}$と表すと、$A$と$A^{-1}$の関係を以下のように表すことができます。

$$A^{-1}A=AA^{-1}=E$$

この場合、$A$は行と列の数が等しい**正方行列**である必要があります。

例えば以下の2つの行列はどの順番で行列積を計算しても単位行列になるので、お互いに逆行列の関係になります。

$$C = \left(
    \begin{array}{ccc}
      1 & 1 \\
      1 & 2 \\
    \end{array}
  \right)
D = \left(
    \begin{array}{ccc}
      2 & -1 \\
      -1 & 1 \\
    \end{array}
  \right)  
$$

$$
CD = DC = \left(
    \begin{array}{ccc}
      1 & 0 \\
      0 & 1 \\
    \end{array}
  \right)  
$$

### 行列式
行列によっては、逆行列が存在しない場合があります。逆行列が存在するかどうかは、**行列式**により判定することができます。  
以下の行列を考えます。

$$A = \left(
    \begin{array}{ccc}
      a & b \\
      c & d \\
    \end{array}
  \right) $$

行列式は$|A|$もしくは$\det A$と表されますが、以下の式で表されます。  

$$|A| = \det A = ad-bc$$

この行列式が0である場合、逆行列は存在しません。

例えば以下の行列は$1\times 4 - 2\times 3 = -2$なので逆行列が存在します。  

$$A = \left(
    \begin{array}{ccc}
      1 & 2 \\
      3 & 4 \\
    \end{array}
  \right) $$
  
一方、以下の行列は$1\times 0 - 2\times 0 = 0$なので逆行列が存在しません。

$$A = \left(
    \begin{array}{ccc}
      1 & 2 \\
      0 & 0 \\
    \end{array}
  \right) $$
  
逆行列が存在する場合、以下の公式により逆行列を求めることができます。

$$A^{-1} = \frac{1}{ad-bc}\left(
    \begin{array}{ccc}
      d & -b \\
      -c & a \\
    \end{array}
  \right) $$

### 行列式の実装
Numpyのlinalg.det関数により、行列式を求めることができます。

In [20]:
a = np.array([[1, 2],
             [3, 4]])

mat1 = sp.Matrix(a)
mat1_d = sp.det(mat1)

print(f'行列式が0である場合、逆行列は存在しない\n')
print(f'a行列:\n\n{a}\n\naの行列式: {np.linalg.det(a)}\n')
display(mat1, mat1_d)

b = np.array([[1, 2],
             [0, 0]])

mat2 = sp.Matrix(b)
mat2_d = sp.det(mat2)

print(f'\n行列式が0である場合、逆行列は存在しない\n')
print(f'b行列:\n\n{b}\n\naの行列式: {np.linalg.det(b)}\n')
display(mat2, mat2_d)



行列式が0である場合、逆行列は存在しない

a行列:

[[1 2]
 [3 4]]

aの行列式: -2.0000000000000004



⎡1  2⎤
⎢    ⎥
⎣3  4⎦


行列式が0である場合、逆行列は存在しない

b行列:

[[1 2]
 [0 0]]

aの行列式: 0.0



⎡1  2⎤
⎢    ⎥
⎣0  0⎦

### 逆行列の実装
逆行列が存在する場合、NumPyのlinalg.inv関数により逆行列を求めることができます。

In [19]:
a = np.array([[1, 2],
             [3, 4]])

mat1 = sp.Matrix(a)
mat1_d = sp.det(mat1)
mat1_i = mat1.inv()

print(f'\n行列式が0である場合、逆行列は存在しない\n')
print(f'a行列:\n\n{a}\n\na行列式： {np.linalg.det(a)}\n\naの逆行列:\n\n{np.linalg.inv(a)}\n')
display(mat1, mat1_d,  mat1_i)


行列式が0である場合、逆行列は存在しない

a行列:

[[1 2]
 [3 4]]

a行列式： -2.0000000000000004

aの逆行列:

[[-2.   1. ]
 [ 1.5 -0.5]]



⎡1  2⎤
⎢    ⎥
⎣3  4⎦

⎡-2    1  ⎤
⎢         ⎥
⎣3/2  -1/2⎦

より行数、列数の多い正方行列に対して逆行列を手計算する場合は、吐き出し法、余因子法などを用いますが、少々複雑になります。  
このような場合でも、NumPyのlinalg.inv関数を使えば簡単に逆行列を求めることができます。  

逆行列は、人工知能において変数同士の相関関係を調べる回帰分析に使われます。

### 演習:
以下のセルで行列aの行列式を求め、逆行列が存在する場合は逆行列を求めましょう。

In [22]:
import numpy as np

a = np.array([[1, 1],
              [1, 2]])

mat1 = sp.Matrix(a)
mat1_d = mat1.det()
mat1_i = mat1.inv()

print(f'\n行列式が0である場合、逆行列は存在しない\n')
print(f'a行列:\n\n{a}\n\na行列式: {np.linalg.det(a)}\n')
display(mat1, mat1_d)


# 逆行列
print(f'\naの逆行列:\n\n{np.linalg.inv(a)}\n')
display(mat1_i)


行列式が0である場合、逆行列は存在しない

a行列:

[[1 1]
 [1 2]]

a行列式: 1.0



⎡1  1⎤
⎢    ⎥
⎣1  2⎦


aの逆行列:

[[ 2. -1.]
 [-1.  1.]]



⎡2   -1⎤
⎢      ⎥
⎣-1  1 ⎦