# ベクトル演算の演習問題

ここでは，ベクトルの演算についての演習を行います．
これらの問題について，最初に紙に書いて手計算で解いてください．その後でPythonを使って解いてください． 最初からPythonで解いてしまうと考え方が頭の中で定着しませんので，手間はかかりますがまずは手計算を実施してください．

### 問題1

ベクトルに関する次の計算を実施せよ．

$4\left(\begin{array}{c} 8 \\ 5 \end{array} \right) =$

$\left(\begin{array}{c} -48 \\ 30 \end{array} \right)\div 3 =$

$\left(\begin{array}{c} 10 \\ 20 \end{array} \right) + \left(\begin{array}{c} 1 \\ 2 \end{array} \right)=$

$\left(\begin{array}{c} -7 \\ 12 \end{array} \right) - \left(\begin{array}{c} -10 \\ 9 \end{array} \right)=$

$\frac{1}{3}\left(\begin{array}{c} 9 \\ 18 \\ 27 \end{array} \right) + 2\left(\begin{array}{c} \frac{1}{2} \\ 4 \\ -3 \end{array} \right)=$

$2\left(\begin{array}{c} 1 \\ i \end{array} \right) - 2i\left(\begin{array}{c} -i \\ 1 \end{array} \right)=$

ここで$i$は虚数単位です．

### 問題2
スカラー$a=\frac{2}{3}$およびベクトル${\bf b}=\left(\begin{array}{c} 18 \\ -4 \end{array} \right)$としたとき，$a{\bf x}-{\bf b}={\bf 0}$となる2次元ベクトル${\bf x}$を求めよ．
ここで，${\bf 0}=\left(\begin{array}{c} 0 \\ 0 \end{array}\right)$である．

*****
## 演習問題の解答

各問題を順番に解いていきます．
最初に手計算で解答し，その後，Pythonによる解答を示します．

Pythonでは配列計算ライブラリーNumPyを使用するので，事前にインポートします．

> <font color=green>import</font> numpy <font color=green>as</font> np

In [1]:
import numpy as np

### 問題1の解答
最初の計算問題です．

<font color=green>$4\left(\begin{array}{c} 8 \\ 5 \end{array} \right)$</font>
$=
\left(\begin{array}{c} 4\times8 \\ 4\times5 \end{array} \right) =
\left(\begin{array}{c} 32 \\ 20 \end{array} \right)$

となります．
この計算をPythonで確認します．
計算式の中にNumPyの配列定義を直接記載します．

> 4 * np.array([8,5])

In [2]:
4 * np.array([8, 5])

array([32, 20])

2番目の計算問題です．

<font color=green>$\left(\begin{array}{c} -48 \\ 30 \end{array} \right)\div 3$</font>
$=
\left(\begin{array}{c} -48\div3 \\ 30\div3 \end{array} \right) =
\left(\begin{array}{c} -16 \\ 10 \end{array} \right)$

となります．
Pythonでは次の通りです．

> np.array([-48,30]) / 3

In [4]:
np.array([-48, 30]) / 3

array([-16.,  10.])

3番目の計算問題です．

<font color=green>$\left(\begin{array}{c} 10 \\ 20 \end{array} \right) + \left(\begin{array}{c} 1 \\ 2 \end{array} \right)$</font>
$=
\left(\begin{array}{c} 10+1 \\ 20+2 \end{array} \right) =
\left(\begin{array}{c} 11 \\ 22 \end{array} \right)$

となります．Pythonでは次の通りです．

> np.array([10,20]) + np.array([1,2])

In [5]:
np.array([10, 20]) + np.array([1, 2])

array([11, 22])

4番目の計算問題です．

<font color=green>$\left(\begin{array}{c} -7 \\ 12 \end{array} \right) - \left(\begin{array}{c} -10 \\ 9 \end{array} \right)$</font>
$=
\left(\begin{array}{c} -7 - (-10) \\ 12 - 9 \end{array} \right) =
\left(\begin{array}{c} 3 \\ 3 \end{array} \right)$

Codeセルに次のように記載して実行ボタンをクリックします．

> np.array([-7,12]) - np.array([-10,9])

In [6]:
np.array([-7, 12]) - np.array([-10, 9])

array([3, 3])

5番目の計算問題です．

<font color=green>
$\frac{1}{3}\left(\begin{array}{c} 9 \\ 18 \\ 27 \end{array} \right) + 2\left(\begin{array}{c} \frac{1}{2} \\ 4 \\ -3 \end{array} \right)$
</font>
$=
\left(\begin{array}{c} \frac{1}{3}\times9 \\ \frac{1}{3}\times18 \\ \frac{1}{3}\times27 \end{array} \right) + \left(\begin{array}{c} 2\times\frac{1}{2} \\ 2\times4 \\ 2\times(-3) \end{array} \right) =
\left(\begin{array}{c} 3 \\ 6 \\ 9 \end{array} \right) + \left(\begin{array}{c} 1 \\ 8 \\ -6 \end{array} \right) =
\left(\begin{array}{c} 3+1 \\ 6+8 \\ 9+(-6) \end{array} \right) =
\left(\begin{array}{c} 4\\ 14 \\ 3 \end{array} \right) $

となります．Pythonでは次の通りです．

> (1/3)\*np.array([9,18,27]) + 2\*np.array([1/2,4,-3])

In [7]:
(1/3) * np.array([9, 18, 27]) + 2 * np.array([(1/2), 4, -3])

array([ 4., 14.,  3.])

6番目の計算問題です．

<font color=green>
$2\left(\begin{array}{c} 1 \\ i \end{array} \right) - 2i\left(\begin{array}{c} -i \\ 1 \end{array} \right)$
</font>
$=
\left(\begin{array}{c} 2\times1 \\ 2\times i \end{array} \right) + \left(\begin{array}{c} -2i\times(-i) \\ -2i\times1 \end{array} \right) =
\left(\begin{array}{c} 2 \\ 2i \end{array} \right) + \left(\begin{array}{c} -2 \\ -2i \end{array} \right) =
\left(\begin{array}{c} 2-2 \\ 2i-2i \end{array} \right) =
\left(\begin{array}{c} 0 \\ 0 \end{array} \right) $

となります．Pythonで複素数を含んだ配列計算をしてみましょう．
Pythonでは虚数単位を$\ j \ $で表すことに注意してください．

> 2\*np.array([1,1j]) - 2j\*np.array([-1j,1])

In [8]:
2 * np.array([1, 1j]) - 2j * np.array([-1j, 1])

array([0.+0.j, 0.+0.j])

このように手計算とPythonによる計算結果が一致します．
Pythonの計算結果が整数型にならず浮動小数点が残るところが，実際にコンピュータで計算される特徴が出ています．

## 問題2の解答

まず，計算式 <font color=green>$a{\bf x}-{\bf b}={\bf 0}$</font> を変形してベクトル変数${\bf x}$を求める式にします．

$\begin{eqnarray*}
a{\bf x}-{\bf b} &=& {\bf 0} \\
a{\bf x}-{\bf b}+{\bf b} &=& {\bf 0} + {\bf b} \\
a{\bf x} &=& {\bf b} \\
\frac{1}{a}a{\bf x} &=& \frac{1}{a}{\bf b} \\
{\bf x} &=& \frac{1}{a} {\bf b} 
\end{eqnarray*}$

最後の式にスカラー <font color=green>$a=\frac{2}{3}$</font> および
ベクトル <font color=green>${\bf b}=\left(\begin{array}{c} 18 \\ -4 \end{array} \right)$</font>を代入します．

${\bf x} = \frac{1}{a} {\bf b} =
\frac{1}{\frac{2}{3}} \left(\begin{array}{c} 18 \\ -4 \end{array} \right) =
\frac{3}{2} \left(\begin{array}{c} 18 \\ -4 \end{array} \right) =
\left(\begin{array}{c} \frac{3}{2}\times18 \\ \frac{3}{2}(-4) \end{array} \right) =
\left(\begin{array}{c} 27 \\ -6 \end{array} \right)
$

同じことをPythonで実施します．
ここでは定数aと定数ベクトルbを変数として定義してから計算します．

> a = 2/3<br>
> b = np.array([18,-4])<br>
> (1/a) * b

In [10]:
a = 2/3
b = np.array([18, -4])


x = (1/a) * b
x

array([27., -6.])

以上で，ベクトル演算についての演習問題は終了です．
手で計算することなしにプログラムで計算してしまうと仕組みを脳に定着せずに終わってしまいますので，面倒でも一つ一つ確認しながら進みましょう．
*****