# 重回帰分析の実装
- multiple regression analysis

## 行列演算の基礎
- *一番最適な paramertor を求める事ができる*　=　`評価関数を最小にできる計算`


$$
\omega　=　(X^TX)^{-1}X^Ty
$$
1. ベクトルの定義
1. 行列の定義
1. 転置
1. 逆行列
1. 行列積

In [1]:
import numpy as np

In [22]:
# ベクトルの定義
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [23]:
print(x)

[[1]
 [2]
 [3]]


In [24]:
# 行列の定義
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [25]:
print(X)

[[1 2]
 [3 4]]


In [26]:
# 転置
Xt = X.T
Xt

array([[1, 3],
       [2, 4]])

In [27]:
print(f'ベクトル\n{x}\n行列\n{X}\n転置\n{Xt}')

ベクトル
[[1]
 [2]
 [3]]
行列
[[1 2]
 [3 4]]
転置
[[1 3]
 [2 4]]


In [31]:
# 逆行列
# linear algebra : 線形代数

X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [30]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## 重回帰分析の実装（flow）
### 演習問題

$$
x　=　
\left(
    \begin{array}{c}
    1 & 2 & 3 \\
    1 & 2 & 5 \\
    1 & 3 & 4 \\
    1 & 3 & 9 \\
    \end{array}
\right)
,　
y　=　
\left(
    \begin{array}{c}
    1 \\
    5 \\
    6 \\
    8 \\
    \end{array}
\right)
$$


$$
\omega　=　(X^TX)^{-1}X^Ty
$$


1. $X^TX$ を計算
1. $(X^TX)^{-1}$ を計算(逆行列)
1. $X^Ty$　を計算
1. $\omega　=　(X^TX)^{-1}X^Ty$ に代入して計算していく

In [42]:
# X の定義
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])

# y の定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

# 1. 転置・行列積の計算
XtX =np.dot(X.T, X)

# 2. 逆行列 : linear algebra(線形代数)
X_inv = np.linalg.inv(XtX)

# 3. 転置・行列積
Xty = np.dot(X.T, y)


print(f'X:\n{X}\n\ny:\n{y}\n\nXtX: 転置・行列積\n{XtX}\n\nX_inv: 逆行列\n{X_inv}\n\nXty: 転置・行列積\n{Xty}')

X:
[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]

y:
[[1]
 [5]
 [6]
 [8]]

XtX: 転置・行列積
[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]

X_inv: 逆行列
[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]

Xty: 転置・行列積
[[ 20]
 [ 70]
 [124]]


### 4.　$\omega　=　(X^TX)^{-1}X^Ty$ に代入して計算していく

In [43]:
w = np.dot(X_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]
