# Scikit-learn で実装

### 演習問題

$$
x　=　
\left(
    \begin{array}{c}
    1 & 2 & 3 \\
    1 & 2 & 5 \\
    1 & 3 & 4 \\
    1 & 3 & 9 \\
    \end{array}
\right)
,　
y　=　
\left(
    \begin{array}{c}
    1 \\
    5 \\
    6 \\
    8 \\
    \end{array}
\right)
$$


$$
\omega　=　(X^TX)^{-1}X^Ty
$$


1. $X^TX$ を計算
1. $(X^TX)^{-1}$ を計算(逆行列)
1. $X^Ty$　を計算
1. $\omega　=　(X^TX)^{-1}X^Ty$ に代入して計算していく

In [4]:
import numpy as np

In [9]:
# X の定義
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])

# y の定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

# 1. 転置・行列積の計算
XtX =np.dot(X.T, X)

# 2. 逆行列 : linear algebra(線形代数)
X_inv = np.linalg.inv(XtX)

# 3. 転置・行列積
Xty = np.dot(X.T, y)

print(f'X:\n{X}\n\ny:\n{y}\n\nXtX: 転置・行列積\n{XtX}\n\nX_inv: 逆行列\n{X_inv}\n\nXty: 転置・行列積\n{Xty}')

# 4. w を求める
w = np.dot(X_inv, Xty)
print(f'\nw: \n{w}')

X:
[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]

y:
[[1]
 [5]
 [6]
 [8]]

XtX: 転置・行列積
[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]

X_inv: 逆行列
[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]

Xty: 転置・行列積
[[ 20]
 [ 70]
 [124]]

w: 
[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


## 上記を Sciki-learn で実装

In [13]:
# 重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

# model の宣言 : class　でいう instance化
# model = LinearRegression()
# 行列の先頭(index:0)1をれた場合は
model = LinearRegression(fit_intercept= False)

# model の学習 : dataに基づいて paramertorの調整
model.fit(X, y)

LinearRegression(fit_intercept=False)

In [14]:
# 調整後の paramertor 
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [15]:
model.intercept_

0.0

### model を予想して終わりではない
- <u>機械学習はそれを使用して実績を得てなんぼの世界</u>
    

- **そもそもどのくらいの精度なか？**
    - *本当に使用できるくらいの精度が出ているのか?*

In [16]:
# 予測精度 : 決定係数 / 0:論外 1:凄く良い
model.score(X, y)

0.6923076923076923

- 上手くいっているかどうかも直ぐに確認ができる

In [18]:
# 予測値の計算
x = np.array([[1, 2, 3]])

y_pred = model.predict(x)
y_pred

array([[3.]])