# Numpy

### 高速な線形代数のライブラリ
- <u>**線形代数のための行列**</u>
    - *array, zeros, ones, eye などの行列*


- <u>**便利で高速な演算**</u>
    - ベクトル演算やブロードキャスト・統計処理


- <u>**乱数系 module**</u>


- <u>**配列の便利な操作**</u>
    - 条件抽出, file入出力


- <u>**線形代数用の関数**</u>
    - 逆行列を求める、固有値を求める

## 行列の生成

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [4]:
print(arr1)

[1 2 3]


In [5]:
arr2 = np.array([4, 5, 6])

In [6]:
arr1 + arr2

array([5, 7, 9])

In [7]:
arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
arr3.shape

(3, 2)

In [10]:
arr3.shape[0]

3

In [11]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# -1 で 1次元配列に直す事ができる
arr3.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.empty([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# 正規分布に従う　: 平均値が０, 標準偏差が±1
np.random.randn(3, 3)

array([[-1.09543108, -1.57584427, -1.28825637],
       [-0.6038241 , -1.02287948,  0.63187352],
       [ 1.02508182, -0.83051028,  1.25701745]])

## 行列のindex, bool index参照

In [23]:
arr1 = np.arange(9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
arr1[3]

3

In [25]:
arr1[-1]

8

In [26]:
arr1[:4]

array([0, 1, 2, 3])

In [28]:
arr1[4:]

array([4, 5, 6, 7, 8])

In [29]:
arr2 = np.arange(9).reshape([3, 3])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
arr2[0, 0]

0

In [31]:
arr2[0, 1]

1

In [33]:
arr2[:1]

array([[0, 1, 2]])

In [34]:
arr2[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [35]:
arr2 > 4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [37]:
arr2[arr2 > 4]

array([5, 6, 7, 8])

## ユニバーサル関数
- 複数の要素に作用させる関数

In [38]:
3 * arr1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [40]:
arr1 + 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [42]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

- **多くの数学関数はユニバーサル関数なので for loop を回さなくても取得できる**

## 行列のfile入出力

In [43]:
arr1 = np.loadtxt("./resources/brownian_x.csv", delimiter=',')

ValueError: could not convert string to float: ''

- **読み込む file の先頭行の空白が原因**
    - *先頭行を飛ばす処理を行う*

In [44]:
arr1 = np.loadtxt('./resources/brownian_x.csv', delimiter=',', skiprows=1)

In [45]:
arr1

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  2.66089704e+00,  3.08680751e-01, ...,
        -1.24374269e+00,  5.18966400e-01, -1.19367115e+00],
       [ 2.00000000e+00,  3.59851470e+00,  1.08084394e-01, ...,
         7.50444067e-01,  1.61610718e+00, -1.55848791e+00],
       ...,
       [ 4.98000000e+02, -1.13628276e+01, -6.02762346e+00, ...,
         1.06451172e+01,  4.51958909e+01, -1.51173229e+01],
       [ 4.99000000e+02, -1.06156906e+01, -4.98423594e+00, ...,
         1.12467625e+01,  4.48587528e+01, -1.55841110e+01],
       [ 5.00000000e+02, -1.10646530e+01, -3.83636751e+00, ...,
         1.30337334e+01,  4.55136299e+01, -1.32733199e+01]])

In [46]:
arr1.shape

(501, 101)

In [47]:
np.savetxt('./test.csv', arr1, delimiter=',')

## 行列の評価・操作

In [48]:
arr1 = np.arange(10).reshape(5, 2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [49]:
arr1.mean()

4.5

In [50]:
arr1.mean(axis=0)

array([4., 5.])

In [52]:
arr1.mean(axis=1)

array([0.5, 2.5, 4.5, 6.5, 8.5])

- **mear( )**
    - 行列の全ての要素に対しての平均
    - **axis=0**
        - 各列に対しての平均
    - **axis=1**
        - 各行に対しての平均

In [54]:
# 標準偏差 : 通常の標準偏差(N=各要素数,で割ったかたち)
arr1.std()

2.8722813232690143

In [57]:
# 普遍標準偏差 : (N-1の要素数で割った数)
# arr1.std(ddof=True)
arr1.std(ddof=1)

3.0276503540974917

In [59]:
arr2 = np.random.randn(100)
arr2

array([ 0.77451176,  0.00463072, -0.07740994,  0.51324514,  0.55859066,
        0.83709201,  1.48819711, -0.8865836 ,  0.93336286, -1.13103507,
       -0.92906109,  0.02793426,  1.17223595, -0.45005947,  0.48535128,
        0.44821854,  0.92341511, -0.57493909, -0.47569578,  0.36001121,
       -0.389434  ,  1.05926781, -0.93060686,  0.80159963, -0.06110665,
        0.42397664,  1.21894968,  0.20194693, -0.10899278,  0.45675234,
        0.14193721, -1.13811895,  0.60279256,  1.22082948,  0.43419308,
       -1.3249806 ,  0.59309343,  0.85923432, -0.88518841,  0.13262874,
        0.82842642,  0.57732295, -0.60149982, -0.32359819, -0.87872457,
       -1.22289772,  1.41663059,  0.9861931 , -1.00490279,  1.31948459,
       -0.05574796, -1.18928487, -0.43097986, -1.07505031, -0.21960008,
        0.28461613,  1.2434067 ,  0.31289196,  0.24780287, -0.12998066,
       -1.81928518, -1.67259046,  1.76612357, -0.85813153,  0.54967706,
        1.01717064,  1.76057772, -0.81330749, -1.42495397, -2.01

In [61]:
# 最大値
arr2.max()

1.7661235715537986

In [62]:
# 最小値
arr2.min()

-2.1048361560772664

In [63]:
# 昇順
np.sort(arr2)

array([-2.10483616, -2.01019766, -2.00247391, -1.94433607, -1.88325579,
       -1.81928518, -1.67259046, -1.42495397, -1.408565  , -1.40001086,
       -1.3249806 , -1.22289772, -1.18928487, -1.15052415, -1.13811895,
       -1.13103507, -1.07505031, -1.00490279, -0.93060686, -0.92906109,
       -0.8865836 , -0.88518841, -0.87872457, -0.85813153, -0.81330749,
       -0.78513848, -0.71471541, -0.67769561, -0.60337135, -0.60149982,
       -0.57493909, -0.47569578, -0.47261822, -0.45005947, -0.43097986,
       -0.389434  , -0.32359819, -0.21960008, -0.20090846, -0.15795324,
       -0.12998066, -0.10899278, -0.10240598, -0.08634307, -0.07740994,
       -0.06110665, -0.05574796,  0.00231396,  0.00463072,  0.02793426,
        0.13262874,  0.14193721,  0.20194693,  0.24780287,  0.28461613,
        0.31289196,  0.36001121,  0.36865966,  0.42397664,  0.43419308,
        0.44821854,  0.45675234,  0.47204173,  0.48535128,  0.51324514,
        0.54229525,  0.54967706,  0.55859066,  0.57732295,  0.59

In [64]:
# 正　= 1, 負 = -1
np.where(arr2 > 0, 1, -1)

array([ 1,  1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1, -1,  1,  1,  1,
       -1, -1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  1,
        1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1, -1,
       -1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1,  1,  1,  1, -1,
       -1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1,  1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1])

In [65]:
arr2

array([ 0.77451176,  0.00463072, -0.07740994,  0.51324514,  0.55859066,
        0.83709201,  1.48819711, -0.8865836 ,  0.93336286, -1.13103507,
       -0.92906109,  0.02793426,  1.17223595, -0.45005947,  0.48535128,
        0.44821854,  0.92341511, -0.57493909, -0.47569578,  0.36001121,
       -0.389434  ,  1.05926781, -0.93060686,  0.80159963, -0.06110665,
        0.42397664,  1.21894968,  0.20194693, -0.10899278,  0.45675234,
        0.14193721, -1.13811895,  0.60279256,  1.22082948,  0.43419308,
       -1.3249806 ,  0.59309343,  0.85923432, -0.88518841,  0.13262874,
        0.82842642,  0.57732295, -0.60149982, -0.32359819, -0.87872457,
       -1.22289772,  1.41663059,  0.9861931 , -1.00490279,  1.31948459,
       -0.05574796, -1.18928487, -0.43097986, -1.07505031, -0.21960008,
        0.28461613,  1.2434067 ,  0.31289196,  0.24780287, -0.12998066,
       -1.81928518, -1.67259046,  1.76612357, -0.85813153,  0.54967706,
        1.01717064,  1.76057772, -0.81330749, -1.42495397, -2.01

- **np.where( )**
    - *特定の条件を満たすものを振り分ける*
    - 演算を利用して bool index としても利用可能

In [66]:
np.where(arr2 > 0)

(array([ 0,  1,  3,  4,  5,  6,  8, 11, 12, 14, 15, 16, 19, 21, 23, 25, 26,
        27, 29, 30, 32, 33, 34, 36, 37, 39, 40, 41, 46, 47, 49, 55, 56, 57,
        58, 62, 64, 65, 66, 70, 72, 85, 86, 87, 88, 90, 91, 92, 93, 96, 97,
        98, 99]),)

In [67]:
arr2[np.where(arr2 > 0)]

array([0.77451176, 0.00463072, 0.51324514, 0.55859066, 0.83709201,
       1.48819711, 0.93336286, 0.02793426, 1.17223595, 0.48535128,
       0.44821854, 0.92341511, 0.36001121, 1.05926781, 0.80159963,
       0.42397664, 1.21894968, 0.20194693, 0.45675234, 0.14193721,
       0.60279256, 1.22082948, 0.43419308, 0.59309343, 0.85923432,
       0.13262874, 0.82842642, 0.57732295, 1.41663059, 0.9861931 ,
       1.31948459, 0.28461613, 1.2434067 , 0.31289196, 0.24780287,
       1.76612357, 0.54967706, 1.01717064, 1.76057772, 0.36865966,
       0.54229525, 1.26085638, 0.47204173, 0.00231396, 0.63430275,
       0.71626172, 1.47677514, 1.40221719, 1.29084331, 0.61501396,
       0.66854766, 0.61247588, 1.2185001 ])

In [69]:
# 要素数を確認 : 重複は省かれる　/ ユニークな値
arr3 = np.array([1, 2, 3, 4, 5, 2, 4, 5, 7, 8, 2, 4])
np.unique(arr3)

array([1, 2, 3, 4, 5, 7, 8])