# Object型(オブジェクト型)

Pythonにおいて実数は，float型ないしはint型の数値として扱われます． Pythonでは変数のデータ型を明示的に指定しませんが，変数に数値を代入することによって適切なデータ型になります．

オブジェクトのデータ型は，type()関数の引数に対象となるオブジェクトを渡すことによって確認できます．
type()関数の構文は次の通りです．

> <font color=green>type(<font color=blue>*object*</font>)</font>

Codeセルに次のように記入して実行してみましょう．

> type(123)

In [1]:
type(123)

int

Codeセルに次のように記入して実行してみましょう．

> type(12.3)

In [2]:
type(12.3)

float

Codeセルに次のように記入して実行してみましょう．

> type(1+1j)

In [3]:
type(1+1j)

complex

複素数の表現で分かるように<font color=blue>Pythonでは虚数単位を $i$ ではなく $j$ </font>を用いている点に気を付けてください． また， $1+j$ と記載すると $j$ を変数と認識してしまうので， $j$ の前には必ず数値を明記することにも注意してください．

*****
# ベクトル

Pythonでベクトルおよび行列を扱うにはNumPyライブラリーを利用します．
次のインポート文にてNumPyライブラリーを利用可能にします．

> <font color=green>import</font> numpy <font color=green>as</font> np

ここで別名にnpを指定していますが，Pythonの利用者の間では慣用的に使われている別名ですので，私たちもこの別名を使うことにします．

In [4]:
import numpy as np

さて，Pythonにおいてベクトルはndarrayオブジェクトとして保有します．
例として3次元のベクトル (1,2,3) を持つndarrayオブジェクトの変数myArrayを生成します．

> myArray = np.array([1,2,3])  
> myArray

In [5]:
ndarray = np.array([1,2,3])
ndarray

array([1, 2, 3])

この変数のオブジェクト型を確認します．

> type(myArray)

In [6]:
type(ndarray)

numpy.ndarray

Pythonを使うことによって，大きなベクトルも簡単に作ることができます．
例として，1から10を値として持つベクトルを定義してみます．

> np.array(range(1,11))

In [8]:
ndarray1 = np.array(range(1,11))
ndarray1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

*****
# 行列

行列はNumPyの二重配列によって定義します．
例として，次の3行4列の行列を定義します．

$\left(\begin{array}{cc}
1 & 2 & 3 & 4 \\ 
5 & 6 & 7 & 8 \\ 
9 & 10 & 11 & 12 \\
\end{array} \right)$

> myMatrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])  
> myMatrix

In [9]:
myMatrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
myMatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

2行3列目の要素にアクセスしてみましょう．ただし，Pythonのインデックスは0から始まるので，<font color=blue>行と列のインデックスの値をそれぞれ-1して指定する</font>必要があります．

> myMatrix[1,2]

In [10]:
myMatrix[1,2]

7

以上です．
*****